Repository jenkinsci/adobe-cloud-manager-plugin, pull requests merged in 2021-06, with the labels that each got.

#11 Fix link in readme
  README.md
Labels: documentation

#12 Improve highlighting in readme
  doc/config/adobeio-project/README.md
Labels: documentation

#10 Add missing restart test category.
  src/test/java/io/jenkins/plugins/adobe/cloudmanager/step/PipelineStepStateStepTest.java
Labels: bug

#13 Add missing CD file.
  .mvn/extensions.xml
Labels: bug

#14 Improve link to issue tracker
  README.md
Labels: documentation

#17 Fix dependencies.
  pom.xml
Labels: bug

#18 Remove JGit version from properties.
  pom.xml
Labels: dependencies
